[settings]
# Ref: https://mise.jdx.dev/configuration/settings.html#status.missing_tools
status.missing_tools = "never"

trusted_config_paths = [
  "~/projects",
]

[tools]
aws-cli = { version = "2", symlink_bins = "true" }
cookiecutter = "2"
copier = "9"
cosign = "latest"
dive = "latest"
doctl = "1"
doppler = "latest"
glab = "1"
granted = "latest"
hcl2json = "latest"
helm = "3"
jnv = "0"
k9s = "latest"
kubectl = "1.34"
lazydocker = "latest"
"pipx:bump-my-version" = "1"
"pipx:bump2version" = "1"
python = "3.13"
shellcheck = "0"
uv = "latest"
vault = "1.20"
yq = "4"
