[settings]
trusted_config_paths = [
  "~/projects/flaudisio",
  "~/projects/labs",
]

[tools]
aws-cli = { version = "2", symlink_bins = "true" }
cookiecutter = "2"
copier = "9"
cosign = "latest"
dive = "latest"
doctl = "1"
doppler = "latest"
fzf = "latest"
glab = "1"
granted = "latest"
hcl2json = "latest"
helm = "3"
jnv = "latest"
k9s = "latest"
kubectl = "1.34"
kubectx = "latest"
lazydocker = "latest"
python = "3.13"
shellcheck = "latest"
uv = "latest"
vault = "1.20"
yq = "4"
